# fly.toml app configuration file generated for fly-autoscaler-temporal-scaler on 2024-04-05T12:10:25-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-autoscaler-temporal-scaler'
primary_region = 'ord'

[build]
  image = 'flyio/fly-autoscaler:pr-25'

[env]
  FAS_APP_NAME = 'fly-autoscaler-temporal-worker'
  FAS_CREATED_MACHINE_COUNT = 'running_workflow_count / 2'
  FAS_REGIONS = 'iad,ord,sjc'
  FAS_TEMPORAL_ADDRESS = 'integration.lyeth.tmprl.cloud:7233'
  FAS_TEMPORAL_NAMESPACE = 'integration.lyeth'
  FAS_TEMPORAL_METRIC_NAME = 'running_workflow_count'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9090
  path = '/metrics'
